# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-06 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TwoName', models.CharField(max_length=100)),
                ('ThreeTitle', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd',
            },
        ),
        migrations.CreateModel(
            name='DD_ccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_ccj',
            },
        ),
        migrations.CreateModel(
            name='DD_fhchf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_fhchf',
            },
        ),
        migrations.CreateModel(
            name='DD_lsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_lsy',
            },
        ),
        migrations.CreateModel(
            name='DD_scj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_scj',
            },
        ),
        migrations.CreateModel(
            name='DD_sjj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_sjj',
            },
        ),
        migrations.CreateModel(
            name='DD_txzf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_txzf',
            },
        ),
        migrations.CreateModel(
            name='DD_zckdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_zckdj',
            },
        ),
        migrations.CreateModel(
            name='DD_zyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_zyj',
            },
        ),
        migrations.CreateModel(
            name='DD_zz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_dd_zz',
            },
        ),
        migrations.CreateModel(
            name='GL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TwoName', models.CharField(max_length=100)),
                ('ThreeTitle', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl',
            },
        ),
        migrations.CreateModel(
            name='GL_ccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_ccj',
            },
        ),
        migrations.CreateModel(
            name='GL_fhchf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_fhchf',
            },
        ),
        migrations.CreateModel(
            name='GL_lsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_lsy',
            },
        ),
        migrations.CreateModel(
            name='GL_scj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_scj',
            },
        ),
        migrations.CreateModel(
            name='GL_sjj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_sjj',
            },
        ),
        migrations.CreateModel(
            name='GL_txzf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_txzf',
            },
        ),
        migrations.CreateModel(
            name='GL_zckdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_zckdj',
            },
        ),
        migrations.CreateModel(
            name='GL_zyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_zyj',
            },
        ),
        migrations.CreateModel(
            name='GL_zz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_gl_zz',
            },
        ),
        migrations.CreateModel(
            name='nongyou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=20)),
                ('passwd', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=16)),
                ('state', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NYWZ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TwoName', models.CharField(max_length=100)),
                ('ThreeTitle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'myweb_nywz',
            },
        ),
        migrations.CreateModel(
            name='NYWZ_dps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_nywz_dps',
            },
        ),
        migrations.CreateModel(
            name='NYWZ_nm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_nywz_nm',
            },
        ),
        migrations.CreateModel(
            name='NYWZ_qt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_nywz_qt',
            },
        ),
        migrations.CreateModel(
            name='NYWZ_tp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_nywz_tp',
            },
        ),
        migrations.CreateModel(
            name='NYWZ_yp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_nywz_yp',
            },
        ),
        migrations.CreateModel(
            name='One_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TwoTitle', models.CharField(max_length=100)),
                ('OneName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'myweb_one_title',
            },
        ),
        migrations.CreateModel(
            name='SD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TwoName', models.CharField(max_length=100)),
                ('ThreeTitle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'myweb_sd',
            },
        ),
        migrations.CreateModel(
            name='SD_ccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreeName', models.CharField(max_length=100)),
                ('FourTitle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'myweb_sd_ccj',
            },
        ),
        migrations.CreateModel(
            name='SD_CCJ_djccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_ccj_djccj',
            },
        ),
        migrations.CreateModel(
            name='SD_CCJ_ebccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_ccj_ebccj',
            },
        ),
        migrations.CreateModel(
            name='SD_CCJ_ptccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_ccj_ptccj',
            },
        ),
        migrations.CreateModel(
            name='SD_CCJ_ybccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_ccj_ybccj',
            },
        ),
        migrations.CreateModel(
            name='SD_CCJ_ympwccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_ccj_ympwccj',
            },
        ),
        migrations.CreateModel(
            name='SD_fhchf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_fhchf',
            },
        ),
        migrations.CreateModel(
            name='SD_fqf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_fqf',
            },
        ),
        migrations.CreateModel(
            name='SD_hf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_hf',
            },
        ),
        migrations.CreateModel(
            name='SD_scj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_scj',
            },
        ),
        migrations.CreateModel(
            name='SD_sjj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_sjj',
            },
        ),
        migrations.CreateModel(
            name='SD_syj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_syj',
            },
        ),
        migrations.CreateModel(
            name='SD_tcf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_tcf',
            },
        ),
        migrations.CreateModel(
            name='SD_ymf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_ymf',
            },
        ),
        migrations.CreateModel(
            name='SD_zckdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_zckdj',
            },
        ),
        migrations.CreateModel(
            name='SD_zyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ThreeName', models.CharField(max_length=100)),
                ('FourTitle', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'myweb_sd_zyj',
            },
        ),
        migrations.CreateModel(
            name='SD_ZYJ_gzwhj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_zyj_gzwhj',
            },
        ),
        migrations.CreateModel(
            name='SD_ZYJ_jzj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_zyj_jzj',
            },
        ),
        migrations.CreateModel(
            name='SD_ZYJ_zzbyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_zyj_zzbyj',
            },
        ),
        migrations.CreateModel(
            name='SD_zz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_sd_zz',
            },
        ),
        migrations.CreateModel(
            name='YM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TwoName', models.CharField(max_length=100)),
                ('ThreeTitle', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym',
            },
        ),
        migrations.CreateModel(
            name='YM_ccj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_ccj',
            },
        ),
        migrations.CreateModel(
            name='YM_fhchf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_fhchf',
            },
        ),
        migrations.CreateModel(
            name='YM_lsy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_lsy',
            },
        ),
        migrations.CreateModel(
            name='YM_scj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_scj',
            },
        ),
        migrations.CreateModel(
            name='YM_sjj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_sjj',
            },
        ),
        migrations.CreateModel(
            name='YM_txzf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_txzf',
            },
        ),
        migrations.CreateModel(
            name='YM_zckdj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_zckdj',
            },
        ),
        migrations.CreateModel(
            name='YM_zyj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_zyj',
            },
        ),
        migrations.CreateModel(
            name='YM_zz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'myweb_ym_zz',
            },
        ),
    ]
